import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './component/header/stylehead.css'
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

  // export const metadata: Metadata = {
  //   title: "Facebook",
  //   description: "Generated by create next app",
  // };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="_9dls __fb-light-mode" lang="en">
      {/* <Head>
        <link
          rel="icon"
          href="../favicon/Facebook_Logo_Primary.png"  // Path to the PNG favicon in the public directory
          type="image/png"
        />
      </Head> */}
      <body className={inter.className&&"_6s5d _71pn system-fonts--body segoe"}>{children}</body>
    </html>
  );
}
